[package]
name = "simple-fs-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simplefs = {path="../simple-fs"}
spin = "0.7.0"